// 奖品信息表
export let prizeInfo = [
  {
    id: 0,
    num: 1,
    name: "现金奖1",
    typeTitle: "现金奖",
    img: "8888元.svg",
    content: "（1人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 1,
    num: 1,
    name: "现金奖2",
    typeTitle: "现金奖",
    img: "5000元.svg",
    content: "（1人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 2,
    num: 1,
    name: "一等奖",
    typeTitle: "一等奖",
    img: "award1.png",
    content: "Macbook（1人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 3,
    num: 2,
    name: "二等奖",
    typeTitle: "二等奖",
    img: "award2.png",
    content: "Dyson无绳吸尘器（2人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 4,
    num: 2,
    name: "三等奖",
    typeTitle: "三等奖",
    img: "award3.png",
    content: "Dyson吹风机（2人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 5,
    num: 2,
    name: "四等奖1",
    typeTitle: "四等奖",
    img: "award4-1.png",
    content: "扫地机器人（2人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 6,
    num: 3,
    name: "四等奖2",
    typeTitle: "四等奖",
    img: "award4-2.png",
    content: "switch游戏机（3人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 7,
    num: 3,
    name: "五等奖1",
    typeTitle: "五等奖",
    img: "award5-1.png",
    content: "无线蓝牙麦克风（3人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 8,
    num: 3,
    name: "五等奖2",
    typeTitle: "五等奖",
    img: "award5-2.png",
    content: "无线耳机（3人）",
    luckusers: [],
    btnshow: true,
  },
  {
    id: 9,
    num: 10,
    name: "五等奖3",
    typeTitle: "五等奖",
    img: "award5-3.png",
    content: "带薪假期3天（10人）",
    luckusers: [],
    btnshow: true,
  },
];
